### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by tiagomartinho** [mull-project/mull#352]
Hello everyone!

If I run the tests both from the command line:

` make test `

And from the Xcode project (scheme MullUnitTests) I get the following error:

> : CommandLine Error: Option 'rewrite-map-file' registered more than once!
> LLVM ERROR: inconsistency in registered CommandLine options
> Program ended with exit code: 1

Can you help me running the tests? 

Thanks in advance!

**Comment by AlexDenisov** [comment]
Hi @tiagomartinho.
Thank you for reporting this issues, I have hit it recently as well.
For now, you may consider one of these to options:
1. Switch to an older compiler to compile Mull: anything before `AppleClang 9.1.0.9020039` should work.
2. Ignore failing tests (🙈) and continue using `mull-driver`, since it's not affected by the issue.

**Comment by tiagomartinho** [comment]
Allright! Thanks a lot @AlexDenisov !

**Comment by AlexDenisov** [comment]
Hi @tiagomartinho, just a follow up: the issue was (partially) fixed, you can now run the tests with any compiler :)

**Comment by tiagomartinho** [comment]
Thanks @AlexDenisov !
