### ISSUE TITLE
GoogleTest: tests crash when linked against gtest main & co

### ISSUE THREAD

**Issue by chgans** [mull-project/mull#535]
We link our tests this way:
```
target_link_libraries(AISUnitTests
    PRIVATE
        GTest::GTest
        GTest::Main
        GTest::GMock
        GTest::GMockMain
)
```

When i run mull on them they all crash.

After looking at the example, i've changed them to embedded gtest-all and gtest_main.

The problem is that we have hundred of tests all built the same way.

Our pattern is one unit test cpp file per tested class, each containing several TEST(), and then we link everything against gtest/gmock. We have more complex setup as well.

Is this a supported config? And so a bug in mull?

As well, after changing one oy my tests to follow the example, i've noticed unexpected behaviour.
it looks like the coverage is extracted from executing the whole testsuite, but then the mutant killing is done  on a per testcase. mull kept reporting non-killed mutant b/c one testcase is not sensitive to code executed by another testcase.
The only way around was to tell mull that this was a custom test. This way mull executed the whole binary, and reported the correct mutation score.
An annoying side effect was that unkilled mutant were reported from mutation in gtest code itself.

Am i doing something wrong?

PS: Thank you so much for bringing mutation testing to C++!

**Comment by AlexDenisov** [comment]
Hi @chgans, thanks a lot for the feedback!

> Is this a supported config? And so a bug in mull?

Sounds like a bug in Mull.

> As well, after changing one oy my tests to follow the example, i've noticed unexpected behaviour.
it looks like the coverage is extracted from executing the whole testsuite, but then the mutant killing is done on a per testcase. mull kept reporting non-killed mutant b/c one testcase is not sensitive to code executed by another testcase.
The only way around was to tell mull that this was a custom test. This way mull executed the whole binary, and reported the correct mutation score.

This is also sounds like a bug, Or it could be because of the same reason as in #522. 

> An annoying side effect was that unkilled mutant were reported from mutation in gtest code itself.

This is known, we are working on a set of filters one can use to get rid of this.

> Am i doing something wrong?

From what I see everything is correct, it's just we didn't hit such case before. Could you create a sample project using the approach (`GTest::GTest/GTest::Main`) you mentioned?

**Comment by chgans** [comment]
[mull-issue-535.tar.gz](https://github.com/mull-project/mull/files/3349304/mull-issue-535.tar.gz)

A very simple project, see README.md (assume a Linux box), basically:
- If you use cmake -DINCLUDE_GTEST, everything work
- if not, test executions crash

**Comment by chgans** [comment]
> > The only way around was to tell mull that this was a custom test. This way mull executed the whole binary, and reported the correct mutation score.
> 
> This is also sounds like a bug, Or it could be because of the same reason as in #522.

I was not able to reproduce with a simple test, i'll have to dig deeper

> > Am i doing something wrong?
> 
> From what I see everything is correct, it's just we didn't hit such case before. Could you create a sample project using the approach (`GTest::GTest/GTest::Main`) you mentioned?

See previous comment.

**Comment by AlexDenisov** [comment]
> I was not able to reproduce with a simple test, i'll have to dig deeper

It may happen if you have inline function in a header or if you have several template instantiations.

> A very simple project, see README.md (assume a Linux box), basically:

I will take a look, thanks a lot!

**Comment by AlexDenisov** [comment]
So the recommendation, in this case, would be to either compile everything with `-fembed-bitcode` or use dynamic libraries for such dependencies.
The other option is to teach mull the `-L/foo/bar -lbuzz` trick so that it will behave like a linker, but it requires more work and needs to be implemented properly, which might be non-trivial.

@chgans I'm closing this for now, but feel free to reopen if it's a major blocker for you.
