### ISSUE TITLE
Questions about mutations and object files

### ISSUE THREAD

**Issue by ocornejo** [mull-project/mull#651]
First of all, thanks for Mull!
Second, I've a couple of questions for you:

1. Do you know if could be possible to output the object file with the actual mutations applied? By reading the source code I understand that the mutations are done at runtime and then applied through trampolines. How it could be done?
2. Also, it’s clear that you extract the singular bitcode files using the EBC library from the executable. Do you know if it is possible, after the mutations are applied, to perform the opposite process, that is, from the cached object files to recompose the application’s executable?

Thanks in advance,

**Comment by stanislaw** [comment]
Hi @ocornejo,

thanks for asking!

>    Do you know if could be possible to output the object file with the actual mutations applied? By reading the source code I understand that the mutations are done at runtime and then applied through trampolines. How it could be done?

Mutations are applied on the LLVM bitcode level and then the LLVM bitcode modules with the mutated code compiled into object files (which are essentially `.o` files) and then runtime-linked and run via LLVM JIT in memory. It should definitely be possible to simply dump the object files into files.

>    Also, it’s clear that you extract the singular bitcode files using the EBC library from the executable. Do you know if it is possible, after the mutations are applied, to perform the opposite process, that is, from the cached object files to recompose the application’s executable?

Again, since the mutations end up compiled into object files, it should definitely be possible to link them into final executable. I don't know if it is easily doable using LLVM API but at least it should e possible by running a normal linker on the dumped `.o` files.

What you are asking in both of your questions is something that should be doable but it has not been on our roadmap so far. Could you provide some context why would you want to create such executables from mutated code?

**Comment by stanislaw** [comment]
I am closing this for now. Please reopen if you have further comments.
