### ISSUE TITLE
Crash after `JIT engine could not resolve the following symbols: ___emutls_get_address`

### ISSUE THREAD

**Issue by gebart** [mull-project/mull#743]
This crash happens when trying to start any test program that contains at least one thread local variable. 
The cause of this is that when recompiling the bitcode, all TLS accesses are converted to using TLS emulation. I don't have much knowledge of this area but from what I have managed to find online, this behavior of the JIT engine should be similar to using the `-femulated-tls` flag with clang. Forcing TLS emulation off is possible by modifying the calls to the EngineBuilder in InstrumentedCompilationTask.cpp, but that seems to make the recompilation crash instead.

### Minimal example test subject which shows the problem

```c++
int main(int argc, char **argv) {
  thread_local static int c = 0;
  return c;
}
```

### Example run
```
❯ mull-cxx --debug --test-framework=CustomTest --sandbox=None ./build/HelloWorldTests
[debug] Diagnostics: Debug Mode enabled. Debug-level messages will be printed.
[info] Extracting bitcode from executable (threads: 1)
       [################################] 1/1. Finished in 2ms
[info] Loading bitcode files (threads: 1)
       [################################] 1/1. Finished in 12ms
[info] Compiling instrumented code (threads: 1)
       [################################] 1/1. Finished in 11ms
[info] Loading dynamic libraries (threads: 1)
       [################################] 1/1. Finished in 1ms
[info] Searching tests (threads: 1)
       [################################] 1/1. Finished in 0ms
[info] Preparing original test run (threads: 1)
[warning] JIT engine could not resolve the following symbols:
___emutls_get_address

       [################################] 1/1. Finished in 0ms
[info] Running original tests (threads: 1)
[1]    43292 segmentation fault  mull-cxx --debug --test-framework=CustomTest --sandbox=None
```

Running with sandbox enabled just shows that the test subject has crashed:
```
[warning] Original test failed
test: main
status: Crashed
stdout: ''
stderr: ''
```

### Platform

OS: MacOS 10.15.6 build 19G73
LLVM: clang+llvm-9.0.0-x86_64-darwin-apple from [llvm.org](https://releases.llvm.org/download.html#9.0.0)  (git://github.com/llvm/llvm-project.git 0399d5a9682b3cef71c653373e38890c63c4c365), Target: x86_64-apple-darwin19.6.0

### Analysis

The function `___emutls_get_address` is part of compiler-rt builtins and can be found in `emutls.c.o` in `lib/clang/9.0.0/lib/darwin/libclang_rt.osx.a` (or equivalent), so I tried injecting `emutls.c.o` it via the `precompiledObjects` argument to `mull::Program`, which makes the symbol resolve properly, but it crashes at run time instead. I will spare the steps leading to this but some debugging sessions later and we now know that the emutls.c.o object was compiled for the small or medium code model and it depends on pthread symbols (`pthread_once` etc) which are dynamically loaded out of range from the emutls code which uses `call rel32` for calling the pthread functions which causes the call offset to become truncated so it jumps to an unmapped address instead (-> segfault). The pthread functions and everything dynamically loaded seems to live at `0x7fffxxxxxxxx` when running on my machine, while the test subject and the `precompiledObjects` objects seem to become loaded at `0x1xxxxxxxx`. Recompiling emutls.c from compiler-rt using `-mcmodel=large` and loading that object via `precompiledObjects` allows the emutls code to call pthread functions without crashing. I did try compiling emutls.c with only `-fPIC` but that did not seem to be enough to be enough to fix the jumps.
It seems like everything loaded by `llvm::sys::DynamicLibrary::LoadLibraryPermanently()` called from Driver.cpp gets loaded at fixed addresses around 0x7fffxxxxxxxx, while the test subject and other manually loaded objects become loaded at random offsets (via ASLR, this randomization is disabled when running with a debugger) to addresses starting with 0x1xxxxxxxx.

### Potential workaround or solution

The most straightforward and easy solution IMO is to build the emutls.c file using `-mcmodel=large` as part of mull-cxx and include those when loading the test subject, but this might be considered a bit of a hack. Another option would be to try to get the original test subject built with emulated tls, but I have not yet had any success with this.

**Comment by gebart** [comment]
I figured out an easier solution to the missing symbol is to build a shared library from only emutls.c (normal shared library flags, only `-fPIC`, no `-mcmodel`) and pushing that library onto the end of the dynamic library list in [mull-cxx.cpp](https://github.com/mull-project/mull/blob/0333c4ced2c407e6fffc48f5fda21dc10ab32c8b/tools/mull-cxx/mull-cxx.cpp#L148-L149). That solves the missing symbol issue. 
I will post a PR draft when I have cleaned it up a little.

**Comment by AlexDenisov** [comment]
@gebart thanks a lot for the great report! The PR would be highly appreciated!
Sorry for the delays in communication: busy days :)

**Comment by gebart** [comment]
It would be useful to have some sort of behavior similar to the dynamic linker environment variable `LD_PRELOAD` on Linux ld.so. That would make it easier to inject these kinds of "fixup" libraries without having to recompile mull-cxx.

**Comment by tttteabag** [comment]
I meet this problem too.
My binary (build by llvm-8 itself) was builded with several third-party static libraries(e.g rpc service framework) which were complied by gcc. So when i try to run mull-cxx , all cases were crashed after warning message "JIT engine could not resolve the following symbols:".
I guess this because the third-party static libraries were not complied by clang with flag "-fembed-bitcode". But i could not replace them with shared library because i could not get the source code. any advise ?   

**llvm**:  clang+llvm-8.0.0-x86_64-linux-sles11.3
**mull**:  build from master
**system**:  linux

**error message** :

[debug] Diagnostics: Debug Mode enabled. Debug-level messages will be printed.
[info] Extracting bitcode from executable (threads: 1)
       [################################] 1/1. Finished in 1450ms
[info] Loading bitcode files (threads: 8)
       [################################] 119/119. Finished in 9430ms
[info] Compiling instrumented code (threads: 8)
       [################################] 119/119. Finished in 11ms
[info] Loading dynamic libraries (threads: 1)
       [################################] 1/1. Finished in 2ms
[info] Searching tests (threads: 1)
       [################################] 1/1. Finished in 3ms
[info] Preparing original test run (threads: 1)
[warning] JIT engine could not resolve the following symbols:
_ZN16pk_obj_factory_t11create_uintEj
_ZN8TPLBuild4InitEPv
_ZN13trans_coder_t4initEPKcS1_
_ZNK3taf7TC_Http7getHostEv
_Z20ApiRouteResultUpdateR13QOSREQUESTtagiiRSsP7timeval
_ZTIN3taf11ApplicationE
_ZNK3taf9TC_Config3getERKSsS2_
_ZN6DCache14DCacheClient_RC1Ev
_ZN6DCache14DCacheClient_R9initProxyEN3taf10TC_AutoPtrINS_10ProxyProxyEEE
_ZN3taf9TC_ConfigC1Ev
_ZN3taf9TC_Config9parseFileERKSs
_ZN3taf7ServantC2Ev
......
......
......
_ZN3taf15TC_HttpResponse5resetEv
_ZN3taf14TC_ThreadMutexC1Ev
_ZN3taf10RollWriteTC1Ev

       [################################] 1/1. Finished in 24626ms
[info] Running original tests (threads: 8)
[warning] Original test failed
test: copygbkTest.test_copygbk
status: Crashed
stdout: ''
stderr: ''

       [####----------------------------] 1/8
[warning] Original test failed
test: charUtilTest.test_utf82gbk
status: Crashed
stdout: ''
stderr: ''

       [########------------------------] 2/8
[warning] Original test failed
test: threadDataTest.test_threadData
status: Crashed
stdout: ''
stderr: ''

       [############--------------------] 3/8
[warning] Original test failed
test: realtimeConfTest.test_realtimeconfInit
status: Crashed
stdout: ''
stderr: ''

       [################----------------] 4/8
[warning] Original test failed
test: threadDataTest.test_ShineiAddrChange
status: Crashed
stdout: ''
stderr: ''

       [####################------------] 5/8
[warning] Original test failed
test: threadDataTest.test_GeoConvert
status: Crashed
stdout: ''
stderr: ''

       [########################--------] 6/8
[warning] Original test failed
test: cb2mslogTest.test_getcb2mslog
status: Crashed
stdout: ''
stderr: ''

       [############################----] 7/8
[warning] Original test failed
test: voicedingdangTest.test_navParams
status: Crashed
stdout: ''
stderr: ''

       [################################] 8/8. Finished in 168388ms
[info] No mutants found. Mutation score: infinitely high
[info] Total execution time: 204850ms

**Comment by AlexDenisov** [comment]
Hi @tttteabag, your issue is slightly different.

> I guess this because the third-party static libraries were not complied by clang with flag "-fembed-bitcode". But i could not replace them with shared library because i could not get the source code. any advise ?

Yes, you get it right: the JIT engine needs all the symbols in order to run the tests.
There is some machinery inside of Mull and the corresponding JIT engine which may make it work, but it's tricky and I cannot guarantee that it will work. This machinery is not exposed in the current version of the driver (`mull-cxx`), but I'll add it and ping you when it's done.

**Comment by tttteabag** [comment]
> Hi @tttteabag, your issue is slightly different.
> 
> > I guess this because the third-party static libraries were not complied by clang with flag "-fembed-bitcode". But i could not replace them with shared library because i could not get the source code. any advise ?
> 
> Yes, you get it right: the JIT engine needs all the symbols in order to run the tests.
> There is some machinery inside of Mull and the corresponding JIT engine which may make it work, but it's tricky and I cannot guarantee that it will work. This machinery is not exposed in the current version of the driver (`mull-cxx`), but I'll add it and ping you when it's done.

@AlexDenisov got it, thx!  I am expecting to hear good news.

**Comment by AlexDenisov** [comment]
The main reason for the crash is a missing implementation in the JIT engine. Since the JIT is gone, this should not be an issue anymore.

@tttteabag @gebart please give a try to the new release (0.9.0) and feel free to open new issues for any other problems you hit.
