### ISSUE TITLE
License

### ISSUE THREAD

**Issue by AlexDenisov** [mull-project/mull#76]
We need to choose a license...

**Comment by mbrukman** [comment]
Any update on this? I was just about to file the same issue.

**Comment by stanislaw** [comment]
This is a hot topic about Mull we are actively looking into now. Is there anything that is blocking you from trying Mull without a license at the moment?

**Comment by mbrukman** [comment]
> @mbrukman, this is a hot topic about Mull we are actively looking into now. Is there anything that is blocking you from trying Mull without a license at the moment?

The lack of a license implies "copyrighted with all rights reserved" which legally prevents anyone from doing anything with this repo. This issue has been open for almost a year (since Dec 2016).

Here's what [GitHub says regarding this situation](https://help.github.com/articles/licensing-a-repository/):

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

Downloading a copy of the project's source code == "reproduce" and sharing with a colleague or incorporating into another project == "distribute". Default copyright laws prevent both of those actions.

**Comment by stanislaw** [comment]
> The lack of a license implies "copyrighted with all rights reserved" which legally prevents anyone from doing anything with this repo. This issue has been open for almost a year (since Dec 2016).

We are very much aware of this. The reason of why there is still no license is very simple: we are much better in mutation testing at this point than in understanding the license topic well enough to pick up the right license. We have been actively developing Mull in our spare time since mid of 2016 and our focus was on development side of things. It is only now that we are getting Mull to a usable v1 and it is only now that people are starting to take Mull seriously. Additionally we are talking to people who expressed interest in commercial use of Mull and that adds some complexity to the license question which we have to carefully consider.

I can only repeat that we are actively looking into this and apologise for inconvenience that the absence of license might cause if you want to give Mull a try. We are trying to find the right license as soon as possible.

**Comment by AlexDenisov** [comment]
@mbrukman fixed via #303.

**Comment by mbrukman** [comment]
Thank you, @stanislaw and @AlexDenisov!
